/*
  ____                                   _             _       
 / ___|  ___  _   _ _ __ ___ ___   _ __ | |_   _  __ _(_)_ __  
 \___ \ / _ \| | | | '__/ __/ _ \ | '_ \| | | | |/ _` | | '_ \ 
  ___) | (_) | |_| | | | (_|  __/ | |_) | | |_| | (_| | | | | |
 |____/ \___/ \__,_|_|  \___\___| | .__/|_|\__,_|\__, |_|_| |_|
                                  |_|            |___/         
# A Template for UsbsourcePlugin, a Source Plugin
# Generated by the command: plugin -t source -d ArduinoIO_plugin USBSource
# Hostname: Fram-IV
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-09-02T21:59:15.981+0200
# NOTICE: MADS Version 2.4.3
*/
// Mandatory included headers
#include <source.hpp>
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include <map>
#include <vector>
#include <stdio.h>

// other includes as needed here
#include <arduino_driver/Device.h>
#include <arduino_driver/Enumerator.h>
#include <arduino_driver/Protocol.h>

// Load the namespaces
using namespace std;
using namespace ArduinoDriver;
using json = nlohmann::json;


class USBDriver {
public:
  const map<string, PinMode> modes{
    {"INPUT", PinMode::Input},
    {"OUTPUT", PinMode::Output},
    {"PULLUP", PinMode::InputPullup},
    {"PULLDOWN", PinMode::InputPulldown},
    {"ANALOG", PinMode::AnalogIn},
    {"PWM", PinMode::Pwm},
    {"DAC", PinMode::Dac}
  };

  USBDriver() {
    _dev = make_unique<Device>(open_first(_ctx));
  }

  USBDriver(string serial) {
    _dev = make_unique<Device>(open_by_serial(_ctx, serial));
  }

  ~USBDriver() {
    _dev.reset();
    _dev.release();
    _ctx.reset();
  }

  static string list_devices() {
    auto ctx = std::make_shared<Context>();
    string result;
    EnumerateOptions enum_options;
    enum_options.probe = true;
    enum_options.probe_timeout = std::chrono::milliseconds(500);
    auto devices = ::list_devices(ctx, enum_options);
    for (const auto &dev : devices) {
      if (!dev.identified) {
        continue;
      }
      result += "- " + string(::board_name(dev.info->board_id)) + ", Serial: " + dev.serial + ", VID: " + to_string(dev.vid) + ", PID: " + to_string(dev.pid) + " "  + "\n";
    }
    return result;
  }

protected:
  void read_pin_modes(json obj, const vector<string> &allowed_modes) {
    if (!obj.is_object()) {
      throw runtime_error("Pin modes must be a dictionary");
    }
    for (const auto &[pin, mode] : obj.items()) {
      // read the pin number and mode from the json object
      if (!mode.is_string()) {
        throw runtime_error("Pin mode must be a string");
      }
      string mode_str = mode.get<string>();
      if (modes.find(mode_str) == modes.end()) {
        throw runtime_error("Invalid pin mode: " + mode_str);
      }
      if (!all_of(pin.begin(), pin.end(), ::isdigit)) {
        throw runtime_error("Pin must be a number: " + pin);
      }
      if (find(allowed_modes.begin(), allowed_modes.end(), mode_str) == allowed_modes.end()) {
        throw runtime_error("Pin mode not allowed: " + mode_str);
      }
      _pin_modes[stoi(pin)] = modes.at(mode_str);
      _dev->pin_mode(stoi(pin), modes.at(mode_str));
    }
  }

protected:
  shared_ptr<Context> _ctx = std::make_shared<Context>();
  unique_ptr<Device> _dev;
  string _port{""};
  map<uint8_t, PinMode> _pin_modes{};
  bool _init_error{false};
};


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class UsbsourcePlugin : public Source<json>, public USBDriver {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Source::Source; // inherit constructors

  // Typically, no need to change this.
  // On multi-driver plugins, the kind() is used to select the settings section 
  // in the agent's configuration file.
  string kind() override { return "usbsource"; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: the result is published
  // return_type::retry: go to next loop, nothing is published
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: the result only has a copy of _error
  // return_type::critical: execution stops
  return_type get_output(json &out, vector<unsigned char> *blob = nullptr) override {
    if (_init_error) return return_type::critical;
    out.clear();

    for (const auto &[pin, mode] : _pin_modes) {
      if (mode == PinMode::Input || mode == PinMode::InputPullup || mode == PinMode::InputPulldown) {
        out["digital"][to_string(pin)] = _dev->digital_read(pin);
      } else if (mode == PinMode::AnalogIn) {
        out["analog"][to_string(pin)] = _dev->analog_read_volts(pin);
      }
    }

    if (!_agent_id.empty()) out["agent_id"] = _agent_id;
    return return_type::success;
  }

  void set_params(const json &params) override {
    Source::set_params(params);

    _params["pin_modes"] = json::object();
    _params["pin_modes"]["1"] = "PULLDOWN";

    _params.merge_patch(params);

    try {
      read_pin_modes(_params["pin_modes"], _allowed_pin_modes);
    } catch ( const runtime_error &e) {
      cerr << e.what() << endl;
      _init_error = true;
    }
    
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {
      {"pin modes", _params["pin_modes"].dump()}
    };
    
  };

private:
  // Define the fields that are used to store internal resources
  const vector<string> _allowed_pin_modes{"INPUT", "PULLUP", "PULLDOWN", "ANALOG"};
};

class UsbsinkPlugin : public Sink<json>, public USBDriver {

public:
  // Don't forget to inherit the constructors of the parent class
  // If you really need to implement your own constructor, make sure to call 
  // the parent constructor. Normally, use set_params() to set the parameters
  // instead of the constructor.
  using Sink::Sink; // inherit constructors

  // Typically, no need to change this.
  // On multi-driver plugins, the kind() is used to select the settings section 
  // in the agent's configuration file.
  string kind() override { return "usbsink"; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    if (_init_error) return return_type::critical;
    if (!input.is_object()) {
      _error = "Input must be a JSON object";
      return return_type::error;
    }
    if (input.contains("digital")) {
      for (const auto &[pin_str, value] : input["digital"].items()) {
        if (!all_of(pin_str.begin(), pin_str.end(), ::isdigit)) {
          _error = "Pin must be a number: " + pin_str;
          return return_type::error;
        }
        uint8_t pin = stoi(pin_str);
        if (_pin_modes.find(pin) == _pin_modes.end() || _pin_modes[pin] != PinMode::Output) {
          _error = "Pin not configured as OUTPUT: " + pin_str;
          return return_type::error;
        }
        _dev->digital_write(pin, value.get<bool>());
      }
    }
    if (input.contains("pwm")) {
      for (const auto &[pin_str, value] : input["pwm"].items()) {
        if (!all_of(pin_str.begin(), pin_str.end(), ::isdigit)) {
          _error = "Pin must be a number: " + pin_str;
          return return_type::error;
        }
        uint8_t pin = stoi(pin_str);
        if (_pin_modes.find(pin) == _pin_modes.end() || _pin_modes[pin] != PinMode::Pwm) {
          _error = "Pin not configured as PWM: " + pin_str;
          return return_type::error;
        }
        _dev->pwm_write(pin, value.get<double>());
      }
    }
    if (input.contains("dac")) {
      for (const auto &[pin_str, value] : input["dac"].items()) {
        if (!all_of(pin_str.begin(), pin_str.end(), ::isdigit)) {
          _error = "Pin must be a number: " + pin_str;
          return return_type::error;
        }
        uint8_t pin = stoi(pin_str);
        if (_pin_modes.find(pin) == _pin_modes.end() || _pin_modes[pin] != PinMode::Dac) {
          _error = "Pin not configured as DAC: " + pin_str;
          return return_type::error;
        }
        _dev->dac_write(pin, value.get<double>());
      }
    } 
    return return_type::success;
  }

  void set_params(const json &params) override { 
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    
    try {
      read_pin_modes(_params["pin_modes"], _allowed_pin_modes);
    } catch ( const runtime_error &e) {
      cerr << e.what() << endl;
      _init_error = true;
    }
    _params.merge_patch(params);
    
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {
      {"pin modes", _params["pin_modes"].dump()}
    };
    
  };

private:
  // Define the fields that are used to store internal resources
  const vector<string> _allowed_pin_modes{"OUTPUT", "PWM", "DAC"};
};


/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
MADS_REGISTER_PLUGINS(UsbsourcePlugin, UsbsinkPlugin)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  json output, params;
  
  try {
    cout << "Listing devices..." << endl;
    cout << USBDriver::list_devices() << endl;
  } catch (const DeviceNotFound &e) {
    cerr << "Error: " << e.what() << endl;
  } 
  
  UsbsourcePlugin plugin{};

  // Set example values to params
  params["pin_modes"]["1"] = "PULLDOWN";
  params["pin_modes"]["2"] = "PULLDOWN";
  params["pin_modes"]["3"] = "PULLUP";
  params["pin_modes"]["15"] = "ANALOG";
  

  // Set the parameters
  plugin.set_params(params);

  // Process data
  plugin.get_output(output);

  // Produce output
  cout << "Output: " << output << endl;
  return 0;
}
